=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/_SCHEMA.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "allTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "simpleWithStructTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "struct",
        "string"
      ]
    },
    "noArrayObjectTypes": {
      "enum": [
        "boolean",
        "integer",
        "null",
        "number",
        "string"
      ]
    },
    "noObjectTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "string"
      ]
    },
    "format": {
      "enum": [
        "date",
        "date-time",
        "time",
        "email",
        "idn-email",
        "hostname",
        "idn-hostname",
        "ipv4",
        "ipv6",
        "uri",
        "uri-reference",
        "iri",
        "iri-reference",
        "uri-template",
        "json-pointer",
        "relative-json-pointer",
        "regex"
      ]
    },
    "idString": {
      "type": "string",
      "minLength": 6,
      "maxLength": 128
    },
    "nameString": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "specsDef": {
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "step": {
          "type": "number"
        },
        "unit": {
          "type": "string",
          "minLength": 1,
          "maxLength": 10
        },
        "unitName": {
          "$ref": "#/definitions/nameString"
        },
        "optional": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "oneOf": [{
                    "type": "string"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "boolean"
                  }
                ]
              },
              "desc": {
                "type": "string"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "columnSimple": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/noObjectTypes"
        },
        "columnSimple": {
          "$ref": "#/definitions/columnSimple"
        },
        "columnComplex": {
          "$ref": "#/definitions/columnComplex"
        }
      },
      "additionalProperties": false
    },
    "columnComplex": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      },
      "additionalItems": false
    },
    "parameterDef": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/nameString"
        },
        "required": {
          "type": "boolean"
        },
        "name": {
          "$ref": "#/definitions/nameString"
        },
        "type": {
          "$ref": "#/definitions/simpleWithStructTypes"
        },
        "accessMode": {
          "enum": [
            "ro",
            "rw"
          ]
        },
        "format": {
          "$ref": "#/definitions/format"
        },
        "columnSimple": {
          "$ref": "#/definitions/columnSimple"
        },
        "columnComplex": {
          "$ref": "#/definitions/columnComplex"
        },
        "struct": {
          "$ref": "#/definitions/structDef"
        },
        "specs": {
          "$ref": "#/definitions/specsDef"
        },
        "description": {
          "type": "string"
        },
        "default": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "parametersDef": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      }
    },
    "structDef": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      }
    }
  },
  "$id": "http://7g.cn/schema",
  "type": "object",
  "properties": {
    "productId": {
      "$ref": "#/definitions/idString"
    },
    "productName": {
      "$ref": "#/definitions/nameString"
    },
    "properties": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      },
      "additionalItems": false
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/definitions/nameString"
          },
          "name": {
            "$ref": "#/definitions/nameString"
          },
          "parameters": {
            "$ref": "#/definitions/parametersDef"
          },
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        }
      }
    },
    "services": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/definitions/nameString"
          },
          "name": {
            "$ref": "#/definitions/nameString"
          },
          "timeout": {
            "type": "integer",
            "description": "超时时间,单位毫秒."
          },
          "parameters": {
            "$ref": "#/definitions/parametersDef"
          },
          "output": {
            "$ref": "#/definitions/parametersDef"
          },
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/SPEAKER.json
{
  "productId": "Speaker",
  "productName": "音柱",
  "properties": [{
      "id": "volume",
      "name": "音量",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 100,
        "unit": "dB",
        "unitName": "分贝",
        "step": 1
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "playingProgram",
      "name": "当前播放歌曲",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "playStatus",
      "name": "当前播放状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "正在播放"
          },
          {
            "value": 1,
            "desc": "播放暂停状态"
          },
          {
            "value": 2,
            "desc": "空闲状态"
          }
        ]
      }
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "manual",
            "desc": "手动"
          },
          {
            "value": "auto",
            "desc": "自动"
          }
        ]
      }
    },
    {
      "id": "programsLists",
      "name": "节目列表",
      "accessMode": "ro",
      "required": true,
      "type": "array",
      "columnSimple": {
        "type": "string"
      },
      "specs": {}
    }
  ],
  "events": [],
  "services": [{
      "id": "setVolume",
      "name": "设置音量",
      "type": "business",
      "parameters": [{
        "id": "volume",
        "name": "音量",
        "accessMode": "ro",
        "required": true,
        "type": "integer",
        "specs": {
          "min": 0,
          "max": 100,
          "unit": "db",
          "unitName": "分贝",
          "step": 1
        }
      }],
      "output": []
    },
    {
      "id": "addProgram",
      "name": "添加节目",
      "type": "management",
      "parameters": [{
          "id": "url",
          "name": "下载地址",
          "accessMode": "ro",
          "required": true,
          "type": "string"
        },
        {
          "id": "md5Sum",
          "name": "md5校验值",
          "accessMode": "ro",
          "required": true,
          "type": "string"
        }
      ],
      "output": []
    },
    {
      "id": "delProgram",
      "name": "删除节目",
      "type": "management",
      "parameters": [{
        "id": "md5Sum",
        "name": "md5校验值",
        "accessMode": "ro",
        "required": true,
        "type": "string"
      }],
      "output": []
    },
    {
      "id": "getPrograms",
      "name": "查询节目",
      "type": "management",
      "parameters": [],
      "output": [{
        "id": "md5List",
        "name": "文件MD5列表",
        "accessMode": "ro",
        "required": true,
        "type": "array",
        "columnSimple": {
          "type": "string"
        },
        "specs": {}
      }]
    },
    {
      "id": "playProgram",
      "name": "播放节目",
      "type": "business",
      "parameters": [{
          "id": "md5List",
          "name": "文件MD5列表",
          "accessMode": "ro",
          "required": true,
          "type": "array",
          "columnSimple": {
            "type": "string"
          },
          "specs": {}
        },
        {
          "id": "times",
          "name": "播放次数",
          "accessMode": "ro",
          "required": true,
          "type": "integer",
          "specs": {
            "min": 0,
            "max": 999999,
            "unit": "time",
            "unitName": "次数",
            "step": 1
          }
        }
      ],
      "output": []
    },
    {
      "id": "pauseProgram",
      "name": "暂停播放",
      "type": "business",
      "parameters": [],
      "output": []
    },
    {
      "id": "resumeProgram",
      "name": "继续播放",
      "type": "business",
      "parameters": [],
      "output": []
    },
    {
      "id": "stopProgram",
      "name": "停止播放",
      "type": "business",
      "parameters": [],
      "output": []
    },
    {
      "id": "switchMode",
      "name": "切换模式",
      "type": "management",
      "parameters": [{
        "id": "mode",
        "name": "模式",
        "accessMode": "ro",
        "required": true,
        "type": "string",
        "specs": {
          "optional": [{
              "value": "manual",
              "desc": "手动"
            },
            {
              "value": "auto",
              "desc": "自动"
            }
          ]
        }
      }],
      "output": []
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/PROJECTOR_GC8086.json
{
  "productId": "GC8086",
  "productName": "沃顿投影灯",
  "properties": [{
      "id": "onOff",
      "name": "投影灯状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 1,
            "desc": "开"
          },
          {
            "value": 0,
            "desc": "关"
          }
        ]
      }
    },
    {
      "id": "rs485Addr",
      "name": "rs485地址",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "rs485Port",
      "name": "rs485端口",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 8,
        "step": 1
      }
    },
    {
      "id": "rs485Baund",
      "name": "波特率",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200,
        "step": 1200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "数据位",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 6,
            "desc": "6数据位"
          },
          {
            "value": 7,
            "desc": "7数据位"
          },
          {
            "value": 8,
            "desc": "8数据位"
          }
        ]
      }
    },
    {
      "id": "rs485Parity",
      "name": "校验位",
      "accessMode": "rw",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "停止位",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 1,
            "desc": "1停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "rw",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "manual",
            "desc": "手动"
          },
          {
            "value": "auto",
            "desc": "自动"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "model",
      "name": "设备型号",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "online",
      "name": "离线在线",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "brightness",
      "name": "灯亮度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 100,
        "unit": "%",
        "unitName": "百分值",
        "step": 1
      }
    },
    {
      "id": "beads",
      "name": "珠点亮",
      "accessMode": "ro",
      "required": true,
      "type": "number"
    },
    {
      "id": "flickerFrequency",
      "name": "闪烁频率",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 255,
        "step": 1
      }
    },
    {
      "id": "playPattern",
      "name": "播放图案",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 1,
        "max": 3,
        "step": 1
      }
    },
    {
      "id": "stepperMotor",
      "name": "进步电机",
      "accessMode": "ro",
      "required": true,
      "type": "number"
    }
  ],
  "events": [],
  "services": [{
      "id": "setOnOff",
      "name": "设置开关",
      "parameters": [{
        "id": "onOff",
        "name": "开关",
        "accessMode": "rw",
        "required": true,
        "type": "number",
        "specs": {
          "optional": [{
              "value": 1,
              "desc": "开"
            },
            {
              "value": 0,
              "desc": "关"
            }
          ]
        }
      }],
      "output": []
    },
    {
      "id": "setBrightness",
      "name": "设置亮度",
      "parameters": [{
        "id": "brightness",
        "name": "亮度",
        "accessMode": "rw",
        "required": true,
        "type": "number",
        "specs": {
          "min": 0,
          "max": 255,
          "step": 1
        }
      }],
      "output": []
    },
    {
      "id": "setFlickerFrequency",
      "name": "设置闪烁频率",
      "parameters": [{
        "id": "flickerFrequency",
        "name": "闪烁频率",
        "accessMode": "rw",
        "required": true,
        "type": "number",
        "specs": {
          "min": 0,
          "max": 255,
          "step": 1
        }
      }],
      "output": []
    },
    {
      "id": "switchMode",
      "name": "切换控制模式",
      "parameters": [{
        "id": "mode",
        "name": "控制模式",
        "required": true,
        "type": "string",
        "specs": {
          "optional": [{
              "value": "manual",
              "desc": "手动"
            },
            {
              "value": "auto",
              "desc": "自动"
            }
          ]
        }
      }]
    },
    {
      "id": "setPlayPattern",
      "name": "设置播放图案",
      "parameters": [{
        "id": "playPattern",
        "name": "播放图案",
        "accessMode": "rw",
        "required": true,
        "type": "number",
        "specs": {
          "min": 1,
          "max": 3,
          "step": 1
        }
      }],
      "output": []
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/TRAFFICSCREEN.json
{
  "productId": " S3_DH_ITSXS170127RGAB",
  "productName": "大华交通屏",
  "properties": [{
      "id": "sn",
      "name": "设备sn号",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "width",
      "name": "宽度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 64,
        "max": 4096,
        "unit": "px",
        "unitName": "像素",
        "step": 32
      }
    },
    {
      "id": "height",
      "name": "长度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 64,
        "max": 1536,
        "unit": "px",
        "unitName": "像素",
        "step": 32
      }
    },
    {
      "id": "ip",
      "name": "ip地址",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "online",
      "name": "在线状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "playStatus",
      "name": "播放状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "空闲"
          },
          {
            "value": 1,
            "desc": "在播"
          }
        ]
      }
    },
    {
      "id": "onOff",
      "name": "屏幕状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "关屏"
          },
          {
            "value": 1,
            "desc": "开屏"
          }
        ]
      }
    },
    {
      "id": "playingProgram",
      "name": "正在播放的节目",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "brightness",
      "name": "亮度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 100,
        "step": 1
      }
    },
    {
      "id": "programList",
      "name": "节目列表",
      "accessMode": "ro",
      "required": true,
      "type": "array",
      "columnComplex": [{
        "id": "fileName",
        "name": "节目文件名",
        "type": "string"
      }, {
        "id": "md5",
        "name": "节目的md5",
        "type": "string"
      }]
    },
    {
      "id": "customizeProgramList",
      "name": "节目列表",
      "accessMode": "ro",
      "required": true,
      "type": "array",
      "columnComplex": [{
        "id": "fileName",
        "name": "节目文件名",
        "type": "string"
      }, {
        "id": "md5",
        "name": "节目的md5",
        "type": "string"
      }]
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "auto",
            "desc": "自动"
          },
          {
            "value": "manual",
            "desc": "手动"
          }
        ]
      }
    }
  ],
  "events": [],
  "services": [{
      "id": "setOnOff",
      "name": "开关屏",
      "parameters": [{
        "id": "onOff",
        "name": "开关",
        "required": true,
        "type": "integer",
        "specs": {
          "optional": [{
              "value": 0,
              "desc": "关屏"
            },
            {
              "value": 1,
              "desc": "开屏"
            }
          ]
        }
      }]
    },
    {
      "id": "setBrightness",
      "name": "设置亮度",
      "parameters": [{
        "id": "brightness",
        "name": "亮度",
        "required": true,
        "type": "integer",
        "specs": {
          "min": 0,
          "max": 100,
          "step": 1
        }
      }]
    },
    {
      "id": "addProgram",
      "name": "添加节目",
      "parameters": [{
          "id": "url",
          "name": "节目url地址",
          "required": true,
          "type": "string"
        },
        {
          "id": "fileName",
          "name": "节目名",
          "required": true,
          "type": "string"
        },
        {
          "id": "md5Sum",
          "name": "文件MD5",
          "required": true,
          "type": "string"
        }
      ]
    },
    {
      "id": "delProgram",
      "name": "删除节目",
      "parameters": [{
        "id": "fileName",
        "name": "节目名",
        "required": true,
        "type": "string"
      }]
    },
    {
      "id": "renameProgram",
      "name": "更改节目名",
      "parameters": [{
          "id": "oldProgramName",
          "name": "改动前节目名字",
          "required": true,
          "type": "string"
        },
        {
          "id": "newProgramName",
          "name": "改动后节目名字",
          "required": true,
          "type": "string"
        }
      ]
    },
    {
      "id": "playProgram",
      "name": "播放节目",
      "parameters": [{
        "id": "fileName",
        "name": "节目名",
        "required": true,
        "type": "string"
      }]
    },

    {
      "id": "delCustomizeProgram",
      "name": "删除自定义节目模板",
      "parameters": [{
        "id": "fileName",
        "name": "节目名",
        "required": true,
        "type": "string"
      }]

    },
    {
      "id": "getProgramList",
      "name": "查询节目列表",
      "parameters": [],
      "output": [{
        "id": "programList",
        "name": "节目文件名和md5列表",
        "type": "array",
        "columnComplex": [{
          "id": "fileName",
          "name": "节目文件名",
          "type": "string"
        }, {
          "id": "md5",
          "name": "节目的md5",
          "type": "string"
        }]
      }]
    },
    {
      "id": "getCustomizeProgramList",
      "name": "查询自定义模板节目",
      "parameters": [],
      "output": [{
        "id": "customizeProgramList",
        "name": "模板文件名和md5列表",
        "type": "array",
        "columnComplex": [{
          "id": "fileName",
          "name": "节目文件名",
          "type": "string"
        }, {
          "id": "md5",
          "name": "节目的md5",
          "type": "string"
        }]
      }]
    },
    {
      "id": "addCustomizeProgram",
      "name": "添加自定义节目模板",
      "parameters": [{
          "id": "fileName",
          "name": "节目名",
          "required": true,
          "type": "string"
        },
        {
          "id": "url",
          "name": "模板文件的url地址",
          "required": true,
          "type": "string"
        },
        {
          "id": "md5Sum",
          "name": "模板文件的MD5",
          "required": true,
          "type": "string"
        }
      ]
    },
    {
      "id": "stopProgram",
      "name": "停止播放",
      "parameters": []
    },
    {
      "id": "switchMode",
      "name": "切换控制模式",
      "parameters": [{
        "id": "mode",
        "name": "控制模式",
        "required": true,
        "type": "string",
        "specs": {
          "optional": [{
              "value": "auto",
              "desc": "自动"
            },
            {
              "value": "manual",
              "desc": "手动"
            }
          ]
        }
      }]
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/LOCK_RHL-JGS869.json
{
  "productId": "RHL_JGS869",
  "productName": "瑞隆源机柜锁",
  "properties": [{
      "id": "onOff",
      "name": "开关状态",
      "accessMode": "ro",
      "required": false,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "关闭"
          },
          {
            "value": 1,
            "desc": "开启"
          }
        ]
      }
    },
    {
      "id": "online",
      "name": "在线状态",
      "accessMode": "ro",
      "required": false,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "version",
      "name": "设备软件版本",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "rs485Port",
      "name": "485端口",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 8
      }
    },
    {
      "id": "rs485Addr",
      "name": "设备地址",
      "accessMode": "rw",
      "required": true,
      "type": "string"
    },
    {
      "id": "rs485Baund",
      "name": "波特率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "数据位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 6,
            "desc": "6数据位"
          },
          {
            "value": 7,
            "desc": "7数据位"
          },
          {
            "value": 8,
            "desc": "8数据位"
          }
        ]
      }
    },
    {
      "id": "rs485Parity",
      "name": "校验位",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "停止位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 1,
            "desc": "1停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    }
  ],
  "events": [{
      "id": "lockerInvadeStart",
      "name": "门锁入侵开始",
      "parameters": []
    },
    {
      "id": "lockerInvadeStop",
      "name": "门锁入侵结束",
      "parameters": []
    }
  ],
  "services": [{
      "id": "setOnOff",
      "name": "设置开关锁",
      "type": "business",
      "parameters": [{
        "id": "onOff",
        "name": "开关状态",
        "accessMode": "ro",
        "required": true,
        "type": "integer",
        "specs": {
          "optional": [{
              "value": 0,
              "desc": "关闭"
            },
            {
              "value": 1,
              "desc": "开启"
            }
          ]
        }
      }],
      "output": []
    },
    {
      "id": "setAlarmFrequency",
      "name": "设置告警重复上报频率",
      "type": "management",
      "parameters": [{
        "id": "frequency",
        "name": "告警频率",
        "accessMode": "ro",
        "required": true,
        "type": "integer",
        "specs": {
          "min": 1,
          "max": 9999,
          "unit": "s",
          "unitName": "秒",
          "step": 1
        }
      }],
      "output": []
    },
    {
      "id": "switchMode",
      "name": "切换模式",
      "type": "management",
      "parameters": [{
        "id": "mode",
        "name": "模式",
        "accessMode": "ro",
        "required": true,
        "type": "string",
        "specs": {
          "optional": [{
              "value": "manual",
              "desc": "手动"
            },
            {
              "value": "auto",
              "desc": "自动"
            }
          ]
        }
      }],
      "output": []
    }
  ]
}
