=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/_SCHEMA.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "allTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "simpleWithStructTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "struct",
        "string"
      ]
    },
    "noArrayObjectTypes": {
      "enum": [
        "boolean",
        "integer",
        "null",
        "number",
        "string"
      ]
    },
    "noObjectTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "string"
      ]
    },
    "format": {
      "enum": [
        "date",
        "date-time",
        "time",
        "email",
        "idn-email",
        "hostname",
        "idn-hostname",
        "ipv4",
        "ipv6",
        "uri",
        "uri-reference",
        "iri",
        "iri-reference",
        "uri-template",
        "json-pointer",
        "relative-json-pointer",
        "regex"
      ]
    },
    "idString": {
      "type": "string",
      "minLength": 6,
      "maxLength": 128
    },
    "nameString": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "specsDef": {
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "step": {
          "type": "number"
        },
        "unit": {
          "type": "string",
          "minLength": 1,
          "maxLength": 10
        },
        "unitName": {
          "$ref": "#/definitions/nameString"
        },
        "optional": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "oneOf": [{
                    "type": "string"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "boolean"
                  }
                ]
              },
              "desc": {
                "type": "string"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "columnSimple": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/noObjectTypes"
        },
        "columnSimple": {
          "$ref": "#/definitions/columnSimple"
        },
        "columnComplex": {
          "$ref": "#/definitions/columnComplex"
        }
      },
      "additionalProperties": false
    },
    "columnComplex": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      },
      "additionalItems": false
    },
    "parameterDef": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/nameString"
        },
        "required": {
          "type": "boolean"
        },
        "name": {
          "$ref": "#/definitions/nameString"
        },
        "type": {
          "$ref": "#/definitions/simpleWithStructTypes"
        },
        "accessMode": {
          "enum": [
            "ro",
            "rw"
          ]
        },
        "format": {
          "$ref": "#/definitions/format"
        },
        "columnSimple": {
          "$ref": "#/definitions/columnSimple"
        },
        "columnComplex": {
          "$ref": "#/definitions/columnComplex"
        },
        "struct": {
          "$ref": "#/definitions/structDef"
        },
        "specs": {
          "$ref": "#/definitions/specsDef"
        },
        "description": {
          "type": "string"
        },
        "default": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "parametersDef": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      }
    },
    "structDef": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      }
    }
  },
  "$id": "http://7g.cn/schema",
  "type": "object",
  "properties": {
    "productId": {
      "$ref": "#/definitions/idString"
    },
    "productName": {
      "$ref": "#/definitions/nameString"
    },
    "properties": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      },
      "additionalItems": false
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/definitions/nameString"
          },
          "name": {
            "$ref": "#/definitions/nameString"
          },
          "parameters": {
            "$ref": "#/definitions/parametersDef"
          },
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        }
      }
    },
    "services": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/definitions/nameString"
          },
          "name": {
            "$ref": "#/definitions/nameString"
          },
          "timeout": {
            "type": "integer",
            "description": "超时时间,单位毫秒."
          },
          "parameters": {
            "$ref": "#/definitions/parametersDef"
          },
          "output": {
            "$ref": "#/definitions/parametersDef"
          },
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/S7_FRT_RDM202.json
{
  "productId": "S7_FRT_RDM202",
  "productName": "富奥通202",
  "properties": [
    {
      "id": "minWindDirection",
      "name": "最小风向角度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 360,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "model",
      "name": "设备型号",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "manual",
            "desc": "手动"
          },
          {
            "value": "auto",
            "desc": "自动"
          }
        ]
      }
    },
    {
      "id": "windDirection",
      "name": "平均风向角度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 360,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "maxWindDirection",
      "name": "最大风向角度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 360,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "minWindSpeed",
      "name": "最小风速",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 70,
        "unit": "m/s",
        "unitName": "米每秒"
      }
    },
    {
      "id": "windSpeed",
      "name": "风速",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 70,
        "unit": "m/s",
        "unitName": "米每秒"
      }
    },
    {
      "id": "maxWindSpeed",
      "name": "最大风速",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 70,
        "unit": "m/s",
        "unitName": "米每秒"
      }
    },
    {
      "id": "PM2_5",
      "name": "细颗粒物浓度值",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 1000,
        "unit": "ug/m2",
        "unitName": "ug/m2"
      }
    },
    {
      "id": "PM10",
      "name": "细颗粒物浓度值",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 1000,
        "unit": "ug/m2",
        "unitName": "ug/m2"
      }
    },
    {
      "id": "rs485Port",
      "name": "485端口",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 8
      }
    },
    {
      "id": "rs485Addr",
      "name": "设备地址",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "rs485Baund",
      "name": "波特率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "数据位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 6,
            "desc": "6数据位"
          },
          {
            "value": 7,
            "desc": "7数据位"
          },
          {
            "value": 8,
            "desc": "8数据位"
          }
        ]
      }
    },
    {
      "id": "rs485Parity",
      "name": "校验位",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "停止位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 1,
            "desc": "1停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "online",
      "name": "在线状态",
      "accessMode": "ro",
      "required": false,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    }
  ],
  "services": [
    {
      "id": "switchMode",
      "name": "切换模式",
      "type": "management",
      "parameters": [
        {
          "id": "mode",
          "name": "模式",
          "required": true,
          "type": "string",
          "specs": {
            "optional": [
              {
                "value": "manual",
                "desc": "手动"
              },
              {
                "value": "auto",
                "desc": "自动"
              }
            ]
          }
        }
      ],
      "output": []
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/S6_YM_1031LRKCT.json
{
  "productId": "S6_YM_1031LRKCT",
  "productName": "裕明单灯控制器",
  "properties": [
    {
      "id": "onOff",
      "name": "灯状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 1,
            "desc": "在线"
          },
          {
            "value": 0,
            "desc": "离线"
          }
        ]
      }
    },
    {
      "id": "rs485Addr",
      "name": "rs485地址",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "rs485Port",
      "name": "rs485端口",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 8,
        "step": 1
      }
    },
    {
      "id": "rs485Baund",
      "name": "波特率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200,
        "step": 1200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "数据位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 6,
            "desc": "6数据位"
          },
          {
            "value": 7,
            "desc": "7数据位"
          },
          {
            "value": 8,
            "desc": "8数据位"
          }
        ]
      }
    },
    {
      "id": "rs485Parity",
      "name": "校验位",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "停止位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 1,
            "desc": "1停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "auto",
            "desc": "自动"
          },
          {
            "value": "manual",
            "desc": "手动"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "model",
      "name": "设备model",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "online",
      "name": "离线在线",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "brightness",
      "name": "灯亮度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 100,
        "unit": "%",
        "unitName": "百分值",
        "step": 1
      }
    },
    {
      "id": "voltage",
      "name": "电压",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "unit": "mv",
        "unitName": "毫伏"
      }
    },
    {
      "id": "laekageCurrent",
      "name": "漏电流值",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "unit": "mA",
        "unitName": "漏电安培"
      }
    },
    {
      "id": "totalEnergy",
      "name": "总电能",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "unit": "Wh",
        "unitName": "瓦时"
      }
    },
    {
      "id": "versionNumber",
      "name": "灯控软件版本号",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "current",
      "name": "电流",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "unit": "mA",
        "unitName": "毫安"
      }
    },
    {
      "id": "activePower",
      "name": "功率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "unit": "W",
        "unitName": "瓦特"
      }
    }
  ],
  "events": [],
  "services": [
    {
      "id": "setOnOff",
      "name": "设置开关",
      "parameters": [
        {
          "id": "onOff",
          "name": "开关",
          "accessMode": "ro",
          "required": true,
          "type": "integer",
          "specs": {
            "optional": [
              {
                "value": 1,
                "desc": "开"
              },
              {
                "value": 0,
                "desc": "关"
              }
            ]
          }
        }
      ],
      "output": []
    },
    {
      "id": "setBrightness",
      "name": "设置亮度",
      "parameters": [
        {
          "id": "brightness",
          "name": "亮度",
          "accessMode": "ro",
          "required": true,
          "type": "integer",
          "specs": {
            "min": 0,
            "max": 100,
            "unit": "%",
            "unitName": "百分比",
            "step": 1
          }
        }
      ],
      "output": []
    },
    {
      "id": "switchMode",
      "name": "切换控制模式",
      "parameters": [
        {
          "id": "mode",
          "name": "控制模式",
          "required": true,
          "type": "string",
          "specs": {
            "optional": [
              {
                "value": "auto",
                "desc": "自动"
              },
              {
                "value": "manual",
                "desc": "手动"
              }
            ]
          }
        }
      ]
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/S8_HK_DSPEA22F.json
{
  "productId": "S8_HK_DSPEA22F",
  "productName": "一键报警",
  "properties": [
    {
      "id": "sn",
      "name": "序列号",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "ip",
      "name": "IP地址",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "httpPort",
      "name": "Http端口",
      "accessMode": "ro",
      "required": true,
      "type": "integer"
    },
    {
      "id": "onvifUser",
      "name": "Onvif用户名",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "onvifPassword",
      "name": "Onvif密码",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "online",
      "name": "设备在线/离线状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 1,
            "desc": "在线"
          },
          {
            "value": 0,
            "desc": "离线"
          }
        ]
      }
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "auto",
            "desc": "自动"
          },
          {
            "value": "manual",
            "desc": "手动"
          }
        ]
      }
    },
    {
      "id": "manufacturer",
      "name": "厂商",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "model",
      "name": "型号",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "alarmList",
      "name": "告警事件",
      "accessMode": "ro",
      "required": true,
      "type": "array",
      "columnComplex": [
        {
          "id": "type",
          "name": "告警类型",
          "type": "string",
          "specs": {
            "optional": [
              {
                "value": "alarmIn",
                "desc": "一键报警"
              }
            ]
          }
        },
        {
          "id": "enable",
          "name": "是否订阅",
          "type": "integer",
          "specs": {
            "optional": [
              {
                "value": 1,
                "desc": "告警已订阅"
              },
              {
                "value": 0,
                "desc": "告警未订阅"
              }
            ]
          }
        }
      ]
    }
  ],
  "events": [
    {
      "id": "alarmIn",
      "name": "一键报警",
      "parameters": [
        {
          "id": "type",
          "name": "一键报警onvif告警类型",
          "type": "string",
          "specs": {
            "optional": [
              {
                "value": "alarmIn",
                "desc": "一键报警"
              }
            ]
          }
        },
        {
          "id": "process",
          "name": "告警开始/结束",
          "type": "integer",
          "specs": {
            "optional": [
              {
                "value": 1,
                "desc": "告警开始"
              },
              {
                "value": 0,
                "desc": "告警结束"
              }
            ]
          }
        }
      ]
    }
  ],
  "services": [
    {
      "id": "switchMode",
      "name": "切换手动/自动模式",
      "type": "management",
      "parameters": [
        {
          "id": "mode",
          "name": "模式",
          "type": "string",
          "required": true,
          "specs": {
            "optional": [
              {
                "value": "manual",
                "desc": "手动"
              },
              {
                "value": "auto",
                "desc": "自动"
              }
            ]
          }
        }
      ],
      "output": []
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/S7_RK_RSWSN012.json
{
  "productId": "S7_RK_RSWSN012",
  "productName": "建大仁科温湿度传感器",
  "properties": [
    {
      "id": "model",
      "name": "型号",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "online",
      "name": "在线状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "rs485Addr",
      "name": "rs485地址",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "rs485Port",
      "name": "rs485端口",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 8,
        "step": 1
      }
    },
    {
      "id": "rs485Baund",
      "name": "波特率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200,
        "step": 1200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "数据位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 5,
        "max": 8,
        "step": 1
      }
    },
    {
      "id": "rs485Parity",
      "name": "校验位",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "停止位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 1,
            "desc": "1个停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "manual",
            "desc": "手动"
          },
          {
            "value": "auto",
            "desc": "自动"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    },
    {
      "id": "temperature",
      "name": "温度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -40,
        "max": 80,
        "unit": "℃",
        "unitName": "摄氏度",
        "step": 0.1
      }
    },
    {
      "id": "humidity",
      "name": "湿度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 5,
        "max": 95,
        "unit": "%",
        "unitName": "%"
      }
    }
  ],
  "events": [],
  "services": [
    {
      "id": "switchMode",
      "name": "切换控制模式",
      "parameters": [
        {
          "id": "mode",
          "name": "控制模式",
          "required": true,
          "type": "string",
          "specs": {
            "optional": [
              {
                "value": "manual",
                "desc": "手动"
              },
              {
                "value": "auto",
                "desc": "自动"
              }
            ]
          }
        }
      ]
    }
  ]
}
