=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/_SCHEMA.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "allTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "simpleWithStructTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "struct",
        "string"
      ]
    },
    "noArrayObjectTypes": {
      "enum": [
        "boolean",
        "integer",
        "null",
        "number",
        "string"
      ]
    },
    "noObjectTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "string"
      ]
    },
    "format": {
      "enum": [
        "date",
        "date-time",
        "time",
        "email",
        "idn-email",
        "hostname",
        "idn-hostname",
        "ipv4",
        "ipv6",
        "uri",
        "uri-reference",
        "iri",
        "iri-reference",
        "uri-template",
        "json-pointer",
        "relative-json-pointer",
        "regex"
      ]
    },
    "idString": {
      "type": "string",
      "minLength": 6,
      "maxLength": 128
    },
    "nameString": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "specsDef": {
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        },
        "step": {
          "type": "number"
        },
        "unit": {
          "type": "string",
          "minLength": 1,
          "maxLength": 10
        },
        "unitName": {
          "$ref": "#/definitions/nameString"
        },
        "optional": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "oneOf": [{
                    "type": "string"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "boolean"
                  }
                ]
              },
              "desc": {
                "type": "string"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "columnSimple": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/noObjectTypes"
        },
        "columnSimple": {
          "$ref": "#/definitions/columnSimple"
        },
        "columnComplex": {
          "$ref": "#/definitions/columnComplex"
        }
      },
      "additionalProperties": false
    },
    "columnComplex": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      },
      "additionalItems": false
    },
    "parameterDef": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/nameString"
        },
        "required": {
          "type": "boolean"
        },
        "name": {
          "$ref": "#/definitions/nameString"
        },
        "type": {
          "$ref": "#/definitions/simpleWithStructTypes"
        },
        "accessMode": {
          "enum": [
            "ro",
            "rw"
          ]
        },
        "format": {
          "$ref": "#/definitions/format"
        },
        "columnSimple": {
          "$ref": "#/definitions/columnSimple"
        },
        "columnComplex": {
          "$ref": "#/definitions/columnComplex"
        },
        "struct": {
          "$ref": "#/definitions/structDef"
        },
        "specs": {
          "$ref": "#/definitions/specsDef"
        },
        "description": {
          "type": "string"
        },
        "default": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "parametersDef": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      }
    },
    "structDef": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      }
    }
  },
  "$id": "http://7g.cn/schema",
  "type": "object",
  "properties": {
    "productId": {
      "$ref": "#/definitions/idString"
    },
    "productName": {
      "$ref": "#/definitions/nameString"
    },
    "properties": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameterDef"
      },
      "additionalItems": false
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/definitions/nameString"
          },
          "name": {
            "$ref": "#/definitions/nameString"
          },
          "parameters": {
            "$ref": "#/definitions/parametersDef"
          },
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        }
      }
    },
    "services": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/definitions/nameString"
          },
          "name": {
            "$ref": "#/definitions/nameString"
          },
          "timeout": {
            "type": "integer",
            "description": "超时时间,单位毫秒."
          },
          "parameters": {
            "$ref": "#/definitions/parametersDef"
          },
          "output": {
            "$ref": "#/definitions/parametersDef"
          },
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/SENSOR_ZC_ZCT245RDLBQE277.json
{
  "productId": "S7_ZC_ZCT245RDLBQE277",
  "productName": "直川倾斜传感器",
  "properties": [{
      "id": "xAngle",
      "name": "X轴倾斜角度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "yAngle",
      "name": "Y轴倾斜角度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "xAngleThreshold",
      "name": "X轴倾斜阈值",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "yAngleThreshold",
      "name": "Y轴倾斜阈值",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "rs485Port",
      "name": "rs485端口",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 4,
        "step": 1
      }
    },
    {
      "id": "rs485Addr",
      "name": "rs485设备地址",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "rs485Baund",
      "name": "rs485波特率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "rs485数据位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 5,
        "max": 8,
        "step": 1
      }
    },
    {
      "id": "rs485Parity",
      "name": "rs485校验位",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "rs485停止位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 1,
            "desc": "1停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "online",
      "name": "在线状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "manual",
            "desc": "手动"
          },
          {
            "value": "auto",
            "desc": "自动"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {

      }
    },
    {
      "id": "alarmInterval",
      "name": "告警间隔",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 86400,
        "step": 1,
        "unit": "S",
        "unitName": "秒"
      }
    }
  ],
  "events": [{
      "id": "xTiltAlarm",
      "name": "X轴倾斜告警",
      "parameters": [

      ]
    },
    {
      "id": "yTiltAlarm",
      "name": "Y轴倾斜告警",
      "parameters": [

      ]
    }
  ],
  "services": [{
      "id": "setCurrentAsZero",
      "name": "设置零点模式",
      "parameters": [

      ],
      "output": [

      ]
    },
    {
      "id": "setXAlarmAngleThreshold",
      "name": "设置X轴倾斜阈值",
      "parameters": [{
        "id": "Threshold",
        "name": "X轴倾斜阈值",
        "required": true,
        "type": "integer",
        "specs": {
          "min": 1,
          "max": 45,
          "unit": "°",
          "unitName": "度",
          "step": 1
        }
      }],
      "output": [

      ]
    },
    {
      "id": "setYAlarmAngleThreshold",
      "name": "设置Y轴倾斜阈值",
      "parameters": [{
        "id": "Threshold",
        "name": "Y轴倾斜阈值",
        "required": true,
        "type": "integer",
        "specs": {
          "min": 1,
          "max": 45,
          "unit": "°",
          "unitName": "度",
          "step": 1
        }
      }],
      "output": [

      ]
    },
    {
      "id": "setAlarmInterval",
      "name": "设置告警间隔",
      "parameters": [{
        "id": "interval",
        "name": "告警间隔",
        "required": true,
        "type": "integer",
        "specs": {
          "min": 1,
          "max": 86400,
          "unit": "S",
          "unitName": "秒",
          "step": 1
        }
      }],
      "output": [

      ]
    },
    {
      "id": "switchMode",
      "name": "切换模式",
      "type": "management",
      "parameters": [{
        "id": "mode",
        "name": "模式",
        "required": true,
        "type": "string",
        "specs": {
          "optional": [{
              "value": "manual",
              "desc": "手动"
            },
            {
              "value": "auto",
              "desc": "自动"
            }
          ]
        }
      }],
      "output": [

      ]
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/RFID_XC-RF807-FBT.json
{
  "productId": "XC-RF807-FBT",
  "productName": "远望谷RFID读卡器",
  "properties": [{
      "id": "onOff",
      "name": "RFID状态",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [{
            "value": 1,
            "desc": "开"
          },
          {
            "value": 0,
            "desc": "关"
          }
        ]
      }
    },
    {
      "id": "online",
      "name": "离线在线",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "rw",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "manual",
            "desc": "手动"
          },
          {
            "value": "auto",
            "desc": "自动"
          }
        ]
      }
    },
    {
      "id": "SN",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "model",
      "name": "RFID型号",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "antennaPort",
      "name": "天线端口号",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 4,
        "step": 1
      }
    },
    {
      "id": "macAddress",
      "name": "MAC地址",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "netInfo",
      "name": "以太网信息",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "antennaPortPower",
      "name": "端口功率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 100000,
        "unit": "dbm",
        "unitName": "分贝毫瓦",
        "step": 1
      }
    }
  ],
  "events": [],
  "services": [{
    "id": " switchMode",
    "name": "切换控制模式",
    "parameters": [{
      "id": "mode",
      "name": "控制模式",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [{
            "value": "manual",
            "desc": "手动"
          },
          {
            "value": "auto",
            "desc": "自动"
          }
        ]
      }
    }]
  }]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/SENSOR_ZCT245RD-LBQ-E2-77.json
{
  "productId": "ZCT245RD-LBQ-E2-77",
  "productName": "直川倾斜传感器",
  "properties": [
    {
      "id": "xAngle",
      "name": "X轴倾斜角度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "yAngle",
      "name": "Y轴倾斜角度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "xAngleThreshold",
      "name": "X轴倾斜阈值",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "yAngleThreshold",
      "name": "Y轴倾斜阈值",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -45,
        "max": 45,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "rs485Port",
      "name": "485端口",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 8
      }
    },
    {
      "id": "rs485Addr",
      "name": "设备地址",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 255
      }
    },
    {
      "id": "rs485Baund",
      "name": "波特率",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "数据位",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 6,
            "desc": "6数据位"
          },
          {
            "value": 7,
            "desc": "7数据位"
          },
          {
            "value": 8,
            "desc": "8数据位"
          }
        ]
      }
    },
    {
      "id": "rs485Parity",
      "name": "校验位",
      "accessMode": "rw",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "停止位",
      "accessMode": "rw",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 1,
            "desc": "1停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "online",
      "name": "在线状态",
      "accessMode": "rw",
      "required": false,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    }
  ],
  "events": [
    {
      "id": "xAlarmStart",
      "name": "x轴倾斜告警开始",
      "parameters": []
    },
    {
      "id": "xAlarmStop",
      "name": "x轴倾斜告警结束",
      "parameters": []
    },
    {
      "id": "yAlarmStart",
      "name": "y轴倾斜告警开始",
      "parameters": []
    },
    {
      "id": "yAlarmStop",
      "name": "y轴倾斜告警结束",
      "parameters": []
    }
  ],
  "services": [
    {
      "id": "setZeroMode",
      "name": "设置零点模式",
      "type": "business",
      "parameters": [
        {
          "id": "zeroMode",
          "name": "零点模式",
          "accessMode": "ro",
          "required": true,
          "type": "integer",
          "specs": {
            "optional": [
              {
                "value": 0,
                "desc": "绝对模式"
              },
              {
                "value": 1,
                "desc": "零点模式"
              }
            ]
          }
        }
      ],
      "output": []
    },
    {
      "id": "setXAlarmAngle",
      "name": "设置x轴倾斜阈值",
      "type": "business",
      "parameters": [
        {
          "id": "xAlarmAngle",
          "name": "x轴倾斜阈值",
          "accessMode": "ro",
          "required": true,
          "type": "number",
          "specs": {
            "min": -45,
            "max": 45,
            "unit": "°",
            "unitName": "度",
            "step": 1
          }
        }
      ],
      "output": []
    },
    {
      "id": "setYAlarmAngle",
      "name": "设置y轴倾斜阈值",
      "type": "business",
      "parameters": [
        {
          "id": "yAlarmAngle",
          "name": "y轴倾斜阈值",
          "accessMode": "ro",
          "required": true,
          "type": "number",
          "specs": {
            "min": -45,
            "max": 45,
            "unit": "°",
            "unitName": "度",
            "step": 1
          }
        }
      ],
      "output": []
    },
    {
      "id": "setXAlarmFrequency",
      "name": "设置X轴告警重复上报频率",
      "type": "business",
      "parameters": [
        {
          "id": "frequency",
          "name": "X轴告警频率",
          "accessMode": "ro",
          "required": true,
          "type": "integer",
          "specs": {
            "min": 1,
            "max": 86400,
            "unit": "s",
            "unitName": "秒",
            "step": 1
          }
        }
      ],
      "output": []
    },
    {
      "id": "setYAlarmFrequency",
      "name": "设置y轴告警重复上报频率",
      "type": "business",
      "parameters": [
        {
          "id": "frequency",
          "name": "Y轴告警频率",
          "accessMode": "ro",
          "required": true,
          "type": "integer",
          "specs": {
            "min": 1,
            "max": 86400,
            "unit": "s",
            "unitName": "秒",
            "step": 1
          }
        }
      ],
      "output": []
    },
    {
      "id": "switchMode",
      "name": "切换模式",
      "type": "management",
      "parameters": [
        {
          "id": "mode",
          "name": "模式",
          "accessMode": "ro",
          "required": true,
          "type": "string",
          "specs": {
            "optional": [
              {
                "value": "manual",
                "desc": "手动"
              },
              {
                "value": "auto",
                "desc": "自动"
              }
            ]
          }
        }
      ],
      "output": []
    }
  ]
}

=== Demo-hcy/Gongshi/testbase/library/mqtt_lib/TSL_json/S7_WSL_WXT536.json
{
  "productId": "S7_WSL_WXT536",
  "productName": "维萨拉WXT536",
  "properties": [
    {
      "id": "mode",
      "name": "控制模式",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "auto",
            "desc": "自动模式"
          },
          {
            "value": "manual",
            "desc": "手动模式"
          }
        ]
      }
    },
    {
      "id": "model",
      "name": "设备型号",
      "accessMode": "ro",
      "required": true,
      "type": "string"
    },
    {
      "id": "airPressure",
      "name": "气压",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 600,
        "max": 1100,
        "unit": "Pa",
        "unitName": "帕"
      }
    },
    {
      "id": "tempreture",
      "name": "温度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": -52,
        "max": 62,
        "unit": "°",
        "unitName": "摄氏度"
      }
    },
    {
      "id": "humidity",
      "name": "湿度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 100,
        "unit": "%",
        "unitName": "百分比"
      }
    },
    {
      "id": "windDirection",
      "name": "平均风向角度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 360,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "minWindDirection",
      "name": "最小风向角度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 360,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "maxWindDirection",
      "name": "最大风向角度",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 360,
        "unit": "°",
        "unitName": "度",
        "step": 1
      }
    },
    {
      "id": "minWindSpeed",
      "name": "最小风速",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 60,
        "unit": "m/s",
        "unitName": "米每秒"
      }
    },
    {
      "id": "windSpeed",
      "name": "平均风速",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 60,
        "unit": "m/s",
        "unitName": "米每秒"
      }
    },
    {
      "id": "maxWindSpeed",
      "name": "最大风速",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 60,
        "unit": "m/s",
        "unitName": "米每秒"
      }
    },
    {
      "id": "precipitation",
      "name": "降雨量",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 1000,
        "unit": "M",
        "unitName": "毫米"
      }
    },
    {
      "id": "precipitationPeak",
      "name": "降雨峰值",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 200,
        "unit": "mm/h",
        "unitName": "毫米每小时"
      }
    },
    {
      "id": "precipitationIntensity",
      "name": "降雨强度",
      "accessMode": "ro",
      "required": true,
      "type": "number",
      "specs": {
        "min": 0,
        "max": 60,
        "unit": "m/s"
      }
    },
    {
      "id": "rainingTime",
      "name": "降雨持续时间",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 0,
        "max": 6553500,
        "unit": "s",
        "unitName": "秒"
      }
    },
    {
      "id": "rs485Port",
      "name": "485端口",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1,
        "max": 8
      }
    },
    {
      "id": "rs485Baund",
      "name": "波特率",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "min": 1200,
        "max": 19200
      }
    },
    {
      "id": "rs485DataBit",
      "name": "数据位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 6,
            "desc": "6数据位"
          },
          {
            "value": 7,
            "desc": "7数据位"
          },
          {
            "value": 8,
            "desc": "8数据位"
          }
        ]
      }
    },
    {
      "id": "rs485Parity",
      "name": "校验位",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {
        "optional": [
          {
            "value": "N",
            "desc": "无校验"
          },
          {
            "value": "E",
            "desc": "偶校验"
          },
          {
            "value": "O",
            "desc": "奇校验"
          }
        ]
      }
    },
    {
      "id": "rs485StopBit",
      "name": "停止位",
      "accessMode": "ro",
      "required": true,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 1,
            "desc": "1停止位"
          },
          {
            "value": 2,
            "desc": "2停止位"
          }
        ]
      }
    },
    {
      "id": "online",
      "name": "在线状态",
      "accessMode": "ro",
      "required": false,
      "type": "integer",
      "specs": {
        "optional": [
          {
            "value": 0,
            "desc": "离线"
          },
          {
            "value": 1,
            "desc": "在线"
          }
        ]
      }
    },
    {
      "id": "sn",
      "name": "设备sn",
      "accessMode": "ro",
      "required": true,
      "type": "string",
      "specs": {}
    }
  ],
  "services": [
    {
      "id": "switchMode",
      "name": "切换模式",
      "type": "management",
      "parameters": [
        {
          "id": "mode",
          "name": "模式",
          "accessMode": "ro",
          "required": true,
          "type": "string",
          "specs": {
            "optional": [
              {
                "value": "manual",
                "desc": "手动"
              },
              {
                "value": "auto",
                "desc": "自动"
              }
            ]
          }
        }
      ],
      "output": []
    }
  ]
}
